"use strict";
cc._RF.push(module, '7d800jRKkRGfqSS3fhSet26', 'peizhi');
// Script/peizhi.ts

"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
var _a = cc._decorator, ccclass = _a.ccclass, property = _a.property, requireComponent = _a.requireComponent;
var NewClass = /** @class */ (function (_super) {
    __extends(NewClass, _super);
    function NewClass() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.node1 = null;
        _this.node2 = null;
        _this.node3 = null;
        _this.localTest = false;
        _this.clientTestVersion = "1.0.0";
        _this.testVersion = null;
        return _this;
        //     3月17日 - 3月21日 工作完成内容
        // 1：游戏框架搭建
        // 2：制作18个基础方块预制体 (方块可编辑颜色与道具和状态)
        // 3：完成地图的搭建，可配置8*8以内，任意组合，包括可缺口和障碍物配置
        // 4：完成地图墙面建立，根据 ↑3上面构建的地图自动生成墙体。
        // 5：做完方块的基础移动，跟随手指，遇到方块或者墙壁或者障碍物阻碍移动。
        // 6：方块的自动落点做完11个基础方块的（未做完还差11个）
        // 3月24日 - 3月28日 预计完成目标
        // 1：完成全部方块的落点。
        // 2：完成门的搭建，门可选颜色，可选开关或者星星等特殊状态
        // 3：完成方块通过门的游戏逻辑，使游戏可以最基础运行玩起来
        // 4：出5关版本，配合小白备案审核。
        // 5：根据方块，地图，以及道具，制作地图编辑器 (方块和地图制作的时候都已经考虑到编辑器的需求了) 
        // 	优先制作，后续开发拓展玩法功能时，小白可同步进行制作关卡。
    }
    NewClass.prototype.start = function () {
        // cc.fx.AudioManager.Instance.init();
        // this.testVersion.string = this.clientTestVersion;
        // cc.director.loadScene("GameScene");
        // cc.director.preloadScene("GameScene", ()=>{
        //     // debugger;
        // })
    };
    //判断来源
    NewClass.prototype.containsTrain = function (str) {
        return /from=train/i.test(str);
    };
    //开始游戏，跳转至引导页面
    NewClass.prototype.startGame = function () {
        cc.director.loadScene("GameScene");
        // cc.director.loadScene("GuideScene");
    };
    //备用，用来测试跳转 指定关卡
    NewClass.prototype.clickBtn = function (event, data) {
        cc.fx.GameConfig.GM_INFO.custom = parseInt(data);
        cc.director.loadScene("GameScene");
    };
    //打开排行榜
    NewClass.prototype.openRank = function () {
        cc.director.loadScene("RankScene");
    };
    NewClass.prototype.update = function (dt) {
    };
    __decorate([
        property(cc.Node)
    ], NewClass.prototype, "node1", void 0);
    __decorate([
        property(cc.Node)
    ], NewClass.prototype, "node2", void 0);
    __decorate([
        property(cc.Node)
    ], NewClass.prototype, "node3", void 0);
    __decorate([
        property(false)
    ], NewClass.prototype, "localTest", void 0);
    __decorate([
        property("")
    ], NewClass.prototype, "clientTestVersion", void 0);
    __decorate([
        property(cc.Label)
    ], NewClass.prototype, "testVersion", void 0);
    NewClass = __decorate([
        ccclass
    ], NewClass);
    return NewClass;
}(cc.Component));
exports.default = NewClass;

cc._RF.pop();